### ISSUE TITLE
Issue with registering helpers

### ISSUE THREAD

**Issue by roflomglol** [petebrowne/sprockets-helpers#32]
Hey there!

It's first time I use Sinatra and for dealing with assets I found your gem. I did everything described in "New in 1.0" section and it didn't work.

```
class App < Sinatra::Base
  register Sinatra::Sprockets::Helpers
  set :sprockets, Sprockets::Environment.new(root)
  set :assets_prefix, '/assets'
  set :digest_assets, true

  configure do
    # Setup Sprockets
    sprockets.append_path File.join(root, 'assets', 'stylesheets')
    sprockets.append_path File.join(root, 'assets', 'javascripts')
    sprockets.append_path File.join(root, 'assets', 'images')

    configure_sprockets_helpers do |helpers|
      helpers.asset_host = 'some-bucket.s3.amazon.com'
    end
  end
```

You have a comment there that says it will use 'sprockets', 'public_folder', 'assets_prefix', and 'digest_assets' variables to set up helpers but at least for me, those variables are not defined in time because calling register Sinatra::Sprockets::Helpers happens before those variables are set. Moving this line after setting variables fixes this for me. Am I doing something wrong?

Thanks in advance,
Sergey

**Comment by petebrowne** [comment]
Which version of Sinatra are you using?

There's a [test case](https://github.com/petebrowne/sprockets-helpers/blob/master/spec/sprockets-helpers_spec.rb#L673) for what you're describing, so I'm a little stumped why it isn't working. I think as as long as you call `configure_sprocket_helpers` somewhere *after* setting the variables, it should work.

**Comment by roflomglol** [comment]
It's 1.4.7. The thing is, if I want to explicitly configure with `configure_sprocket_helpers` it does work, but I wanted to just set the variables and let your [gem](https://github.com/petebrowne/sprockets-helpers/blob/master/lib/sinatra/sprockets/helpers.rb#L12) do the rest. But this only works if I register helpers after setting the variables and doesn't if I register it before.

**Comment by petebrowne** [comment]
I see, that's expected behavior at this point. If you look at the [implementation](https://github.com/petebrowne/sprockets-helpers/blob/master/lib/sinatra/sprockets/helpers.rb) you can see why.

You can either do:

``` ruby
class App < Sinatra::Base
  register Sinatra::Sprockets::Helpers
  set :assets_prefix, '/assets'
  set :digest_assets, true
  # Call configure_sprockets_helpers without any arguments to pull in variables from Sinatra
  configure_sprockets_helpers
end
```

or:

``` ruby
class App < Sinatra::Base
  set :assets_prefix, '/assets'
  set :digest_assets, true
  # Register the plugin after setting the sinatra variables
  register Sinatra::Sprockets::Helpers
end
```

I'm not aware of a hook in Sinatra to allow:

``` ruby
class App < Sinatra::Base
  register Sinatra::Sprockets::Helpers
  set :assets_prefix, '/assets'
  set :digest_assets, true
end
```

If you know of one, I'll happily accept a PR

**Comment by roflomglol** [comment]
Oh, well, yeah, it does work if I call configure_sprockets_helpers. Thank you for your time :)
